version: '3'
services:
    php:
      container_name: php
      image: php:7.2-apache
      restart: always
      volumes:
        - .:/var/www/html
      ports:
        - 80:80
      depends_on:
        - db
        - adminer
    db:
      container_name: db
      image: postgres:alpine
      restart: always
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
        - 5432:5432
    adminer:
      container_name: admin
      image: adminer
      restart: always
      ports:
        - 8080:8080